baseURL = "https://example.org/"
languageCode = "en-us"
title = "MFE R Workshop"

# Theme to be use when building the site with Hugo
theme = 'hugo-theme-learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

# global site parameters
[params]
  editURL = ""
  author = "Dan Yavorsky"
  themeVariant = "mine"
  disableSearch = true
  disableInlineCopyToClipBoard = true
  disableNextPrev = true
  disableLandingPageButton = true
