baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-relearn'

[params]
    disableSearch = true
    disableLandingPageButton = true
    ordersectionsby = "weight"
    disableInlineCopyToClipBoard = true
    disableAnchorCopy = true
    disableAnchorScrolling = true

[params.author]
    name = 'Dan Yavorsky'

[[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Zen Light/Dark'